### ISSUE TITLE
platform.system() on MacOS issue

### ISSUE THREAD

**Issue by taspotts** [KAUTH/auto-click-auto#4]
On a few systems I've tested MacOS/OSX is reporting `Darwin`:
```python
>>> import platform
>>> platform.system()
'Darwin'
```

Should be fairly easy to update [core.py](https://github.com/KAUTH/auto-click-auto/blob/main/auto_click_auto/core.py#L46)?
```python
# Check that the program is run on one of the supported Operating Systems
supported_os = ("Linux", "MacOS", "Darwin")
```

I've hacked this change into my `site-packages` for auto_click_auto and it does seem to work okay.

**Comment by KAUTH** [comment]
@taspotts thanks for the contribution!!! 🎉 
I believe you are right, this is something that can be returned by `platform.system()` (https://github.com/python/cpython/blob/main/Lib/platform.py#L1249) and that we want to support.

**Comment by KAUTH** [comment]
@taspotts the new version is out with your fix, https://pypi.org/project/auto-click-auto/0.1.1/
