### ISSUE TITLE
Python 3.11 breaks f-String cast

### ISSUE THREAD

**Issue by fellnerse** [KAUTH/auto-click-auto#9]
When running the auto setup with python 3.11 I get this in the shell:

```fish
❯ ai-tdd setup
Tab autocomplete configuration already setup in ~/.config/fish/completions/ai-tdd.ShellType.FISH.
The ~/.ShellType.ZSHrc configuration file does not exist.
The ~/.ShellType.BASHrc configuration file does not exist.
```

with python 3.10:
```fish
❯ ai-tdd setup
Adding tab autocomplete configuration in ~/.config/fish/completions/ai-tdd.fish ...
Restart or create a new shell session for the changes to take effect.
The ~/.bashrc configuration file does not exist.
The ~/.zshrc configuration file does not exist.
```
I guess the problem is that in 3.11 the automated f string cast [changed](https://discuss.python.org/t/inconsistent-behavior-with-python-3-11-enum-mixin-class-behavior/24613/8)
and all these lines in the core.py are affected:
https://github.com/KAUTH/auto-click-auto/blob/31f526635f8620b5ee720b8ff504287773a94f6f/auto_click_auto/core.py#L88

Can I help here?

**Comment by KAUTH** [comment]
Hey @fellnerse thanks for reporting this! Yes, I can assign it to you if you want. 😃

**Comment by KAUTH** [comment]
From [What’s New In Python 3.11](https://docs.python.org/3/whatsnew/3.11.html#enum)

> Changed [Enum.__format__()](https://docs.python.org/3/library/enum.html#enum.Enum.__format__) (the default for [format()](https://docs.python.org/3/library/functions.html#format), [str.format()](https://docs.python.org/3/library/stdtypes.html#str.format) and [f-string](https://docs.python.org/3/glossary.html#term-f-string)s) to always produce the same result as Enum.__str__(): for enums inheriting from [ReprEnum](https://docs.python.org/3/library/enum.html#enum.ReprEnum) it will be the member’s value; for all other enums it will be the enum and member name (e.g. Color.RED).

**Comment by KAUTH** [comment]
We can rebase the fix on top of https://github.com/KAUTH/auto-click-auto/pull/10 to verify that it works as expected.
